### ISSUE TITLE
Parsing tsconfig.json with support for extra commas

### ISSUE THREAD

**Issue by ZSkycat** [dividab/tsconfig-paths#48]
package.json
```js
  "dependencies": {
    "ts-node": "^6.1.1",
    "tsconfig-paths": "^3.4.0",
    "typescript": "^2.9.2"
  },
```

run command `ts-node -r tsconfig-paths/register.js test.ts`

```cmd
C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\lib\tsconfig-loader.js:72
    var config = JSON.parse(cleanedJson);
                      ^
SyntaxError: Unexpected token } in JSON at position 305
    at JSON.parse (<anonymous>)
    at loadTsconfig (C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\lib\tsconfig-loader.js:72:23)
    at loadSyncDefault (C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\lib\tsconfig-loader.js:27:18)
    at tsConfigLoader (C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\lib\tsconfig-loader.js:13:22)
    at Object.configLoader (C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\lib\config-loader.js:27:22)
    at Object.register (C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\lib\register.js:10:46)
    at Object.<anonymous> (C:\Users\Cat\Desktop\toy-ts-node\node_modules\tsconfig-paths\register.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
```

I really use the command
`cross-env TS_NODE_PROJECT=./tool/tsconfig.json && ts-node -r tsconfig-paths/register ./node_modules/webpack/bin/webpack.js --config ./tool/config.webpack.dev.ts`

`cross-env TS_NODE_PROJECT=./tool/tsconfig.json && node -r tsconfig-paths/register webpack --config ./tool/config.webpack.dev.ts`

I don't know how to use it.

**Comment by ZSkycat** [comment]
I know why.because my tsconfig.json uses jsonc.
https://github.com/TypeStrong/ts-node/issues/409#issuecomment-398583581

But, tsc support jsonc. It would be better to have tsconfig-paths support jsonc.
```
{
    "compilerOptions": {
        "rootDir": ".",
        "outDir": "../dist/tool",
        "target": "esnext",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "strict": true,
        "types": ["node"],
    },
    "include": [
        "./**/*",
    ],
}
```

**Comment by jshado1** [comment]
It looks like `tsconfig` [currently uses `JSON.parse`](https://github.com/TypeStrong/tsconfig/blob/master/src/tsconfig.ts#L195), which would blow chunks on the trailing comma. Odd, because it's from TypeScript, which supports the trailing comma, so I wonder what TypeScript is actually doing…

I haven't tried it yet, but [`Microsoft/node-jsonc-parser`](https://github.com/Microsoft/node-jsonc-parser) might be what the doctor ordered for parsing jsonc.

**Comment by jonaskello** [comment]
IIRC tsconfig-paths currently strips comments and then uses plain JSON.parse(). It would indeed be interesting to know what tsc uses internally to parse tsconfig.json.

**Comment by jonaskello** [comment]
I think json5 is the most popular choice if we should go with an external library. There seems to be a function called `findConfigFile` in the typescript API but not sure if that is useful for actually loading the tsconfig.json file.

**Comment by jshado1** [comment]
@jonaskello make it a peerDependency. If someone is using tsconfig-paths, there's a very good (if not guaranteed?) chance s/he is already using typescript.

**Comment by jonaskello** [comment]
@jshado1 I was thinking the same thing at first. However some ppl use tsconfig-paths in production with something like `node -r  tsconfig-paths/register main.js`. In that case they probably only install `dependencies` with `npm install --production`while typescript is probably is a `devDependency`. So if we require the full typescript package to be installed then usage in production would also require typescript installed.

**Comment by jshado1** [comment]
I think the arguments from babel/register (babel/babel#5851) apply here: The register should not be used in production: It should be pre-compiled, which is actually how I'm trying to use it, paired with [`tspaths`](https://github.com/duffman/tspath). The register is just for developer convenience during actual development (and running specs).

**Comment by jshado1** [comment]
@jonaskello done 🙂

**Comment by jshado1** [comment]
Thanks!

I was hoping to avoid adding a huge dependence like webpack for only 1 tiny feature.

I saw tspaths—the readme sounds exactly like what I want. Unfortunately, it seems to nbe broken :(

**Comment by jonaskello** [comment]
If you really want static path resolving I guess it should not be too hard to do a package that does that. AFAIK tsc does not have a plugin system yet so you would have to compile with tsc first and then replace the paths in the resulting js files. 

The way I would do it would be to use the typescript or babel package to parse the js files into an AST, and look for any `import` or `require` nodes. Then use the API in the tsconfig-path package (`createMatchPath`) to resolve the path for those node and replace them. Since other packages are doing the hard work (parsing and figuring out the new path) I guess it should be fairly simple to implement but of course there could be some pitfalls.

**Comment by jonaskello** [comment]
Did some more research and it seems like you could also achieve static path replacement by writing a plugin to [ttypescript](https://github.com/cevek/ttypescript). That would probably be the simplest and most integrated way available today.
