### ISSUE TITLE
Allow cleanup of register()

### ISSUE THREAD

**Issue by TylorS** [dividab/tsconfig-paths#63]
Hello, first of all thank you for this very useful library! I've been working on some TypeScript tooling myself and this makes using paths some much easier. 

However in testing scenarios it's useful to be able to cleanup some of the side-effects that are being caused by `register`. I'd propose returning a function from `register()` that would reassign `Module._resolveFilename` back to `originalResolveFilename`. I'll happily make the PR if this seems aligned with your goals of this library as well

**Comment by jonaskello** [comment]
I think this seems useful and it should not affect existing users so I don't see any problems adding it.

It does change the API but since the register() function currently returns void I guess it will not really break anyone so I would consider it a minor version increment as it is backwards compatible.

So feel free to go ahead and make a PR for it :-). If you do, please also update the README to reflect the API change.
