### ISSUE TITLE
Problem with import aliases in tsconfig

### ISSUE THREAD

**Issue by farzadmf** [dividab/tsconfig-paths#79]
Hi,

I apologize if I shouldn't ask here, but since I didn't get an answer from Stackoverflow, I thought you might be able to help me:

[here is the question I asked on Stackoverflow](https://stackoverflow.com/questions/55486970/typescript-compiler-tsc-doesnt-recognize-import-aliases)

In a nutshell, I have set up import aliases in my `tsconfig.json`, but when I use `tsc` to compile the code, it's complaining that it cannot find the modules.

I would really, really appreciate if you could help me

**Comment by jonaskello** [comment]
I forked your example repo and added a package.json script for tsc (since I have no global install). See here:

https://github.com/jonaskello/tsc-import-alias-issue

If I run `yarn build`, it actually works without error for me. Could you try this same command? Also which operating system are you using? When testing it I used MacOS.

**Comment by farzadmf** [comment]
Thank you @jonaskello for your answer. I cloned your repo and ran `yarn build`. Right now, I'm using Windows and I'm not sure if I'm missing something, but it doesn't do anything (no JS file is generated). If I change the script to be `"build": "tsc main.ts"`, I see the error that it cannot resolve my import aliases

**Comment by jonaskello** [comment]
The reson that you don't get any output is that you have `"noEmit": true` in tsconfig.json. I changed it to false in my repo and then I get output and also the paths work.

The reason why paths don't work with `tsc main.ts` is that when you pass a file directly to tsc like that, `tsc` will ignore tsconfig.json so no settings from tsconfig.json will be in effect, thus there are no path settings in effect when you run that command. If you like to compile specific files, then put them in `files` or `include` in tsconfig.json. See this link for examples:

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by farzadmf** [comment]
Thank you @jonaskello for the explanation, and yes, you're absolutely right; now it creates the files. Now, my issue becomes a new one!

I changed the `build` script to be something like this: `"build"; "tsc --outDir out"`. When I do `yarn build`, it generates all the files, but when I try to run it like `node out/main.js`, I get the same error:

```
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '@utils/.'
...
```
Is there a way to make sure the resulting Javascript files will have these import aliases resolved as normal paths?

**Comment by jonaskello** [comment]
Unfortunately `tsc` does not support transforming the imports. You basically have two options:

1. Use tsconfig-paths with node like this: `node -r tsconfig-paths/register out/main.js` (see [the docs](https://github.com/dividab/tsconfig-paths#with-node).

2. Build or find a tool that with transform the imports for you.

Closing since the original issue is sorted.

**Comment by farzadmf** [comment]
Thank you @jonaskello for all the help; I appreciate it
